version: "3"
services:
  web:
    image: node
    command: npm start
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db 
  db:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"